# Generated by Django 3.1.6 on 2021-05-31 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('fbid', models.IntegerField(primary_key=True, serialize=False)),
                ('template', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('ivid', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('fid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='interview.feedback')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('jid', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('role', models.BooleanField(default=0)),
                ('phone', models.IntegerField(unique=True)),
                ('jobid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interview.job')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.TextField(max_length=1000)),
                ('comparefile', models.TextField(max_length=20)),
                ('time', models.TimeField()),
                ('title', models.TextField(max_length=20)),
                ('fid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='interview.feedback')),
                ('interviews', models.ManyToManyField(to='interview.Interview')),
            ],
        ),
        migrations.AddField(
            model_name='interview',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.user'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='uid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='interview.user'),
        ),
    ]
