# Generated by Django 3.1.6 on 2021-05-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
