# Generated by Django 3.2 on 2021-06-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20210531_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dreamjob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.TextField(max_length=50)),
                ('skilss_text', models.TextField(blank=True, max_length=1000)),
                ('skills_pic', models.ImageField(blank=True, upload_to=None)),
            ],
        ),
    ]
