# Generated by Django 3.2 on 2021-06-06 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_remove_dreamjob_skills_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dreamjob',
            old_name='skilss_text',
            new_name='skills_text',
        ),
    ]
